version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\ncw\rclone

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - mingw32-make vars
  - mingw32-make build_dep

build_script:
  - mingw32-make quicktest
